spring.application.name=sintese-api

gemini.api-key=${GEMINI_API_KEY}
gemini.url=https://generativelanguage.googleapis.com/v1beta/interactions
gemini.model=gemini-3.8-flash
gemini.api-revision=2026-05-20
gemini.timeout-seconds=15
gemini.thinking-level=low
gemini.temperature=0.1

sintese.max-palavras-entrada=50000
sintese.min-output-tokens-limit=300